#!/bin/bash
# Install and configure Redis with RediSearch module for vector support

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
INSTALL_DIR="${HOME}/.gleitzeit/redis-modules"
REDISEARCH_VERSION="v2.8.12"
REDIS_PORT=6379

# Detect OS and architecture
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

if [ "$ARCH" = "x86_64" ]; then
    ARCH="x64"
elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
    ARCH="arm64"
fi

PLATFORM="${OS}-${ARCH}"
echo -e "${GREEN}Detected platform: ${PLATFORM}${NC}"

# Function to check dependencies
check_dependencies() {
    echo -e "${YELLOW}Checking dependencies...${NC}"
    
    # Check for Redis
    if ! command -v redis-server &> /dev/null; then
        echo -e "${RED}Redis is not installed!${NC}"
        echo "Please install Redis first:"
        if [ "$OS" = "darwin" ]; then
            echo "  brew install redis"
        else
            echo "  sudo apt-get install redis-server"
        fi
        exit 1
    fi
    
    # Check for build tools
    if ! command -v make &> /dev/null; then
        echo -e "${RED}Build tools not found!${NC}"
        if [ "$OS" = "darwin" ]; then
            echo "Installing with Homebrew..."
            brew install cmake make
        else
            echo "Installing with apt..."
            sudo apt-get update
            sudo apt-get install -y build-essential cmake
        fi
    fi
    
    # Check for Git
    if ! command -v git &> /dev/null; then
        echo -e "${RED}Git is not installed!${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ All dependencies satisfied${NC}"
}

# Function to build RediSearch
build_redisearch() {
    echo -e "${YELLOW}Building RediSearch module...${NC}"
    
    # Create install directory
    mkdir -p "$INSTALL_DIR"
    cd "$INSTALL_DIR"
    
    # Clone or update RediSearch
    if [ -d "RediSearch" ]; then
        echo "Updating existing RediSearch repository..."
        cd RediSearch
        git fetch --tags
        git checkout "$REDISEARCH_VERSION"
    else
        echo "Cloning RediSearch repository..."
        git clone --recursive https://github.com/RediSearch/RediSearch.git
        cd RediSearch
        git checkout "$REDISEARCH_VERSION"
    fi
    
    # Build the module
    echo "Building RediSearch..."
    make setup
    make build
    
    # Find the built module
    MODULE_PATH=$(find bin -name "redisearch.so" -type f | head -1)
    
    if [ -z "$MODULE_PATH" ]; then
        echo -e "${RED}Failed to build RediSearch module!${NC}"
        exit 1
    fi
    
    FULL_MODULE_PATH="${INSTALL_DIR}/RediSearch/${MODULE_PATH}"
    echo -e "${GREEN}✓ RediSearch module built: ${FULL_MODULE_PATH}${NC}"
}

# Function to create Redis configuration
create_redis_config() {
    echo -e "${YELLOW}Creating Redis configuration...${NC}"
    
    CONFIG_DIR="${HOME}/.gleitzeit/redis"
    mkdir -p "$CONFIG_DIR"
    
    cat > "${CONFIG_DIR}/redis-vector.conf" << EOF
# Redis configuration with RediSearch vector support
# Generated by Gleitzeit RAG setup

# Load RediSearch module
loadmodule ${FULL_MODULE_PATH}

# Basic configuration
port ${REDIS_PORT}
daemonize no
supervised no
pidfile /var/run/redis_${REDIS_PORT}.pid
loglevel notice
logfile ""

# Persistence
dir ${CONFIG_DIR}/data
dbfilename dump.rdb
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"

# Memory management
maxmemory 2gb
maxmemory-policy noeviction

# Network
bind 127.0.0.1 ::1
protected-mode yes
timeout 0
tcp-keepalive 300

# Performance
rdbcompression yes
rdbchecksum yes
stop-writes-on-bgsave-error yes

# Vector search optimizations
proto-max-bulk-len 512mb
client-output-buffer-limit normal 0 0 0
EOF
    
    echo -e "${GREEN}✓ Configuration created: ${CONFIG_DIR}/redis-vector.conf${NC}"
}

# Function to create start script
create_start_script() {
    echo -e "${YELLOW}Creating start script...${NC}"
    
    SCRIPT_PATH="${HOME}/.gleitzeit/bin/redis-vector"
    mkdir -p "$(dirname "$SCRIPT_PATH")"
    
    cat > "$SCRIPT_PATH" << 'EOF'
#!/bin/bash
# Start Redis with vector support for Gleitzeit

CONFIG_FILE="${HOME}/.gleitzeit/redis/redis-vector.conf"
DATA_DIR="${HOME}/.gleitzeit/redis/data"
LOG_FILE="${HOME}/.gleitzeit/redis/redis-vector.log"

# Create data directory
mkdir -p "$DATA_DIR"

# Check if Redis is already running
if pgrep -f "redis-server.*redis-vector.conf" > /dev/null; then
    echo "Redis with vector support is already running"
    exit 0
fi

# Start Redis
echo "Starting Redis with vector support..."
redis-server "$CONFIG_FILE" 2>&1 | tee -a "$LOG_FILE" &

# Wait for Redis to start
sleep 2

# Verify module is loaded
if redis-cli -p 6379 MODULE LIST | grep -q "search"; then
    echo "✓ Redis started with vector search support on port 6379"
    echo "Log file: $LOG_FILE"
else
    echo "✗ Failed to load RediSearch module"
    exit 1
fi
EOF
    
    chmod +x "$SCRIPT_PATH"
    echo -e "${GREEN}✓ Start script created: ${SCRIPT_PATH}${NC}"
}

# Function to create stop script
create_stop_script() {
    echo -e "${YELLOW}Creating stop script...${NC}"
    
    SCRIPT_PATH="${HOME}/.gleitzeit/bin/redis-vector-stop"
    
    cat > "$SCRIPT_PATH" << 'EOF'
#!/bin/bash
# Stop Redis with vector support

echo "Stopping Redis with vector support..."
redis-cli -p 6379 shutdown

if [ $? -eq 0 ]; then
    echo "✓ Redis stopped successfully"
else
    echo "✗ Failed to stop Redis"
    exit 1
fi
EOF
    
    chmod +x "$SCRIPT_PATH"
    echo -e "${GREEN}✓ Stop script created: ${SCRIPT_PATH}${NC}"
}

# Function to test the installation
test_installation() {
    echo -e "${YELLOW}Testing Redis vector installation...${NC}"
    
    # Start Redis temporarily for testing
    redis-server --loadmodule "${FULL_MODULE_PATH}" --port 6380 --daemonize yes --dir /tmp --pidfile /tmp/redis-test.pid
    
    sleep 2
    
    # Test with Python script
    python3 << 'PYTHON_EOF'
import redis
import sys

try:
    r = redis.Redis(host='localhost', port=6380, decode_responses=True)
    modules = r.module_list()
    
    has_search = any(m.get(b'name', b'').decode() == 'search' for m in modules)
    
    if has_search:
        print("✓ RediSearch module loaded successfully")
        
        # Quick vector test
        from redis.commands.search.field import VectorField, TextField
        from redis.commands.search.indexDefinition import IndexDefinition, IndexType
        
        try:
            r.ft("test_idx").dropindex()
        except:
            pass
        
        schema = [
            TextField("text"),
            VectorField("vec", "FLAT", {
                "TYPE": "FLOAT32",
                "DIM": 10,
                "DISTANCE_METRIC": "COSINE"
            })
        ]
        
        r.ft("test_idx").create_index(
            fields=schema,
            definition=IndexDefinition(prefix=["test:"], index_type=IndexType.HASH)
        )
        
        print("✓ Vector index creation successful")
        r.ft("test_idx").dropindex()
        sys.exit(0)
    else:
        print("✗ RediSearch module not found")
        sys.exit(1)
        
except Exception as e:
    print(f"✗ Test failed: {e}")
    sys.exit(1)
PYTHON_EOF
    
    TEST_RESULT=$?
    
    # Stop test Redis
    redis-cli -p 6380 shutdown
    rm -f /tmp/redis-test.pid
    
    if [ $TEST_RESULT -eq 0 ]; then
        echo -e "${GREEN}✓ Installation test passed${NC}"
    else
        echo -e "${RED}✗ Installation test failed${NC}"
        exit 1
    fi
}

# Function to setup Python environment
setup_python_env() {
    echo -e "${YELLOW}Setting up Python environment...${NC}"
    
    # Check for uv or pip
    if command -v uv &> /dev/null; then
        echo "Installing Python packages with uv..."
        uv pip install redis numpy
    elif command -v pip &> /dev/null; then
        echo "Installing Python packages with pip..."
        pip install redis numpy
    else
        echo -e "${RED}Neither uv nor pip found!${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ Python environment ready${NC}"
}

# Function to add to PATH
update_path() {
    echo -e "${YELLOW}Updating PATH...${NC}"
    
    BIN_DIR="${HOME}/.gleitzeit/bin"
    
    # Add to appropriate shell config
    if [ -n "$BASH_VERSION" ]; then
        RC_FILE="${HOME}/.bashrc"
    elif [ -n "$ZSH_VERSION" ]; then
        RC_FILE="${HOME}/.zshrc"
    else
        RC_FILE="${HOME}/.profile"
    fi
    
    # Check if already in PATH
    if ! grep -q "/.gleitzeit/bin" "$RC_FILE" 2>/dev/null; then
        echo "" >> "$RC_FILE"
        echo "# Gleitzeit Redis vector support" >> "$RC_FILE"
        echo "export PATH=\"\$PATH:${BIN_DIR}\"" >> "$RC_FILE"
        echo -e "${GREEN}✓ Added ${BIN_DIR} to PATH in ${RC_FILE}${NC}"
        echo -e "${YELLOW}  Reload your shell or run: source ${RC_FILE}${NC}"
    fi
}

# Main installation flow
main() {
    echo -e "${GREEN}==================================${NC}"
    echo -e "${GREEN}Gleitzeit Redis Vector Setup${NC}"
    echo -e "${GREEN}==================================${NC}"
    echo
    
    check_dependencies
    build_redisearch
    create_redis_config
    create_start_script
    create_stop_script
    setup_python_env
    test_installation
    update_path
    
    echo
    echo -e "${GREEN}==================================${NC}"
    echo -e "${GREEN}Installation Complete!${NC}"
    echo -e "${GREEN}==================================${NC}"
    echo
    echo "To use Redis with vector support:"
    echo "  Start:  redis-vector"
    echo "  Stop:   redis-vector-stop"
    echo
    echo "Redis will run on port ${REDIS_PORT} with RediSearch module loaded."
    echo
    echo "Module location: ${FULL_MODULE_PATH}"
    echo "Config file: ${HOME}/.gleitzeit/redis/redis-vector.conf"
    echo
    echo -e "${GREEN}You can now use vector search in Gleitzeit RAG!${NC}"
}

# Run main function
main