"""
Authentication setup and migration utilities
"""

import os
import asyncio
import click
import secrets
import yaml
from pathlib import Path
from typing import Optional, Dict, Any
import logging

logger = logging.getLogger(__name__)


def generate_jwt_secret() -> str:
    """Generate a secure JWT secret"""
    return secrets.token_urlsafe(32)


def save_auth_config(config: Dict[str, Any]) -> Path:
    """Save authentication configuration to file"""
    config_dir = Path.home() / ".gleitzeit"
    config_dir.mkdir(parents=True, exist_ok=True)
    
    config_file = config_dir / "config.yaml"
    
    # Load existing config if it exists
    existing_config = {}
    if config_file.exists():
        with open(config_file, 'r') as f:
            existing_config = yaml.safe_load(f) or {}
    
    # Merge with new auth config
    existing_config['auth'] = config
    
    # Save merged config
    with open(config_file, 'w') as f:
        yaml.dump(existing_config, f, default_flow_style=False)
    
    return config_file


def save_env_file(env_vars: Dict[str, str]) -> Path:
    """Save environment variables to .env file"""
    config_dir = Path.home() / ".gleitzeit"
    config_dir.mkdir(parents=True, exist_ok=True)
    
    env_file = config_dir / ".env"
    
    # Read existing env vars if file exists
    existing_vars = {}
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_vars[key] = value
    
    # Update with new vars
    existing_vars.update(env_vars)
    
    # Write back
    with open(env_file, 'w') as f:
        f.write("# Gleitzeit Authentication Configuration\n")
        f.write("# Generated by gleitzeit auth setup\n\n")
        
        for key, value in sorted(existing_vars.items()):
            f.write(f"{key}={value}\n")
    
    return env_file


@click.group()
def auth():
    """Authentication management commands"""
    pass


@auth.command()
def setup():
    """Interactive authentication setup"""
    
    click.echo("🔐 Gleitzeit Authentication Setup")
    click.echo("=" * 40)
    
    # Check if already configured
    config_file = Path.home() / ".gleitzeit" / "config.yaml"
    if config_file.exists():
        try:
            with open(config_file, 'r') as f:
                existing = yaml.safe_load(f) or {}
                if existing.get('auth', {}).get('enabled'):
                    if not click.confirm("Authentication is already configured. Reconfigure?", default=False):
                        return
        except Exception:
            pass
    
    config = {}
    env_vars = {}
    
    # Basic auth setup
    if click.confirm("Enable authentication system?", default=False):
        config['enabled'] = True
        env_vars['GLEITZEIT_AUTH_ENABLED'] = 'true'
        
        # Admin user setup
        click.echo("\n👤 Admin User Setup")
        admin_email = click.prompt("Admin email", default="admin@localhost")
        admin_password = click.prompt(
            "Admin password", 
            hide_input=True, 
            confirmation_prompt=True,
            default="admin"
        )
        
        config['admin_email'] = admin_email
        env_vars['GLEITZEIT_AUTH_ADMIN_EMAIL'] = admin_email
        env_vars['GLEITZEIT_AUTH_ADMIN_PASSWORD'] = admin_password
        env_vars['GLEITZEIT_AUTH_CREATE_ADMIN'] = 'true'
        
        # Generate JWT secret
        jwt_secret = generate_jwt_secret()
        config['jwt_secret'] = jwt_secret
        env_vars['GLEITZEIT_AUTH_JWT_SECRET'] = jwt_secret
        
        # Feature selection
        click.echo("\n⚙️  Feature Configuration")
        
        features = {}
        features['api_keys'] = click.confirm("  Enable API key authentication?", default=True)
        features['jwt'] = click.confirm("  Enable JWT token authentication?", default=True)
        features['sessions'] = click.confirm("  Enable session management?", default=True)
        features['rate_limiting'] = click.confirm("  Enable rate limiting?", default=False)
        features['audit_log'] = click.confirm("  Enable audit logging?", default=False)
        features['ownership_filtering'] = click.confirm("  Enable resource ownership filtering?", default=True)
        features['user_registration'] = click.confirm("  Allow user self-registration?", default=False)
        
        config['features'] = features
        
        # Convert features to env vars
        for feature, enabled in features.items():
            env_key = f"GLEITZEIT_AUTH_{feature.upper()}"
            env_vars[env_key] = str(enabled).lower()
        
        # Persistence selection
        click.echo("\n💾 Storage Configuration")
        storage_choices = {
            '1': ('memory', 'In-memory (development only)'),
            '2': ('sqlite', 'SQLite (single-server production)'),
            '3': ('postgresql', 'PostgreSQL (multi-server production)'),
            '4': ('redis', 'Redis (high-performance caching)')
        }
        
        click.echo("Choose storage backend:")
        for key, (value, desc) in storage_choices.items():
            click.echo(f"  {key}. {value:<12} - {desc}")
        
        choice = click.prompt("Selection", type=click.Choice(storage_choices.keys()), default='1')
        persistence_type = storage_choices[choice][0]
        config['persistence_type'] = persistence_type
        env_vars['GLEITZEIT_PERSISTENCE_TYPE'] = persistence_type
        
        # Additional config for specific backends
        if persistence_type == 'postgresql':
            db_url = click.prompt(
                "PostgreSQL URL",
                default="postgresql://user:pass@localhost/gleitzeit"
            )
            env_vars['GLEITZEIT_DATABASE_URL'] = db_url
        elif persistence_type == 'redis':
            redis_url = click.prompt(
                "Redis URL",
                default="redis://localhost:6379"
            )
            env_vars['GLEITZEIT_REDIS_URL'] = redis_url
        
        # Save configuration
        config_file = save_auth_config(config)
        env_file = save_env_file(env_vars)
        
        click.echo("\n✅ Authentication configured successfully!")
        click.echo(f"📁 Configuration saved to: {config_file}")
        click.echo(f"🔑 Environment file created: {env_file}")
        click.echo("\n📝 Next steps:")
        click.echo("  1. Source the environment file:")
        click.echo(f"     source {env_file}")
        click.echo("  2. Start the server:")
        click.echo("     gleitzeit serve")
        click.echo("  3. Login with admin credentials:")
        click.echo(f"     Email: {admin_email}")
        click.echo("     Password: [hidden]")
        
        if features.get('api_keys'):
            click.echo("\n  4. Generate an API key for programmatic access:")
            click.echo("     curl -X POST http://localhost:8000/auth/api-keys \\")
            click.echo("          -H 'Authorization: Bearer <token>' \\")
            click.echo("          -d '{\"name\": \"My API Key\"}'")
    
    else:
        # No auth configuration
        config['enabled'] = False
        env_vars['GLEITZEIT_AUTH_ENABLED'] = 'false'
        
        config_file = save_auth_config(config)
        env_file = save_env_file(env_vars)
        
        click.echo("\n⚠️  Authentication disabled")
        click.echo("You can enable it later by running: gleitzeit auth setup")
        click.echo(f"\n📁 Configuration saved to: {config_file}")


@auth.command()
@click.option('--admin-email', default='admin@localhost', help='Admin email to assign ownership')
@click.option('--dry-run', is_flag=True, help='Show what would be migrated without making changes')
def migrate(admin_email: str, dry_run: bool):
    """Migrate existing data for authentication"""
    
    # Check if auth is enabled
    if os.getenv("GLEITZEIT_AUTH_ENABLED", "false").lower() != "true":
        click.echo("⚠️  Authentication is not enabled. Enable it first:")
        click.echo("  gleitzeit auth setup")
        return
    
    click.echo("🔄 Starting authentication migration...")
    click.echo(f"📧 Assigning ownership to: {admin_email}")
    
    if dry_run:
        click.echo("🔍 DRY RUN - No changes will be made")
    
    if not dry_run and not click.confirm("This will modify all existing workflows and tasks. Continue?"):
        return
    
    # Run migration
    success = asyncio.run(_migrate_data(admin_email, dry_run))
    
    if success:
        if dry_run:
            click.echo("✅ Dry run completed. Run without --dry-run to apply changes.")
        else:
            click.echo("✅ Migration completed successfully!")
    else:
        click.echo("❌ Migration failed. Check logs for details.")


async def _migrate_data(admin_email: str, dry_run: bool = False) -> bool:
    """
    Migrate existing data to include authentication ownership
    """
    try:
        from ..persistence.factory import get_persistence_backend
        from .database import get_auth_db
        
        logger.info(f"Starting migration (dry_run={dry_run})...")
        
        # Get backends
        persistence = get_persistence_backend()
        auth_db = get_auth_db()
        
        # Get or create admin user
        admin = await auth_db.get_user_by_email(admin_email)
        if not admin:
            if dry_run:
                click.echo(f"ℹ️  Admin user {admin_email} would need to be created")
                admin_id = "admin-dummy-id"
            else:
                click.echo(f"❌ Admin user {admin_email} not found.")
                click.echo("   Run 'gleitzeit auth setup' first to create admin user.")
                return False
        else:
            admin_id = str(admin.id)
            click.echo(f"✓ Found admin user: {admin_email}")
        
        # Migrate workflows
        click.echo("\n📋 Migrating workflows...")
        workflows = await persistence.list_workflows()
        migrated_workflows = 0
        
        for workflow in workflows:
            metadata = workflow.get('metadata', {})
            if not metadata.get('owner_id'):
                if dry_run:
                    click.echo(f"  Would migrate workflow: {workflow.get('id', 'unknown')}")
                else:
                    metadata['owner_id'] = admin_id
                    metadata['owner_email'] = admin_email
                    workflow['metadata'] = metadata
                    await persistence.update_workflow(workflow['workflow_id'], workflow)
                migrated_workflows += 1
        
        click.echo(f"  {'Would migrate' if dry_run else 'Migrated'}: {migrated_workflows} workflows")
        
        # Migrate tasks
        click.echo("\n📝 Migrating tasks...")
        tasks = await persistence.list_tasks()
        migrated_tasks = 0
        
        for task in tasks:
            metadata = task.get('metadata', {})
            if not metadata.get('owner_id'):
                if dry_run:
                    click.echo(f"  Would migrate task: {task.get('id', 'unknown')}")
                else:
                    metadata['owner_id'] = admin_id
                    metadata['owner_email'] = admin_email
                    task['metadata'] = metadata
                    await persistence.update_task(task['task_id'], task)
                migrated_tasks += 1
        
        click.echo(f"  {'Would migrate' if dry_run else 'Migrated'}: {migrated_tasks} tasks")
        
        # Create audit log entry
        if not dry_run:
            await auth_db.create_audit_log(
                user_id=admin_id,
                action="migration",
                resource_type="system",
                details={
                    "migrated_workflows": migrated_workflows,
                    "migrated_tasks": migrated_tasks
                }
            )
        
        click.echo(f"\n📊 Summary:")
        click.echo(f"  Workflows: {migrated_workflows}")
        click.echo(f"  Tasks: {migrated_tasks}")
        
        return True
        
    except Exception as e:
        logger.error(f"Migration failed: {e}")
        click.echo(f"❌ Error during migration: {str(e)}")
        return False


@auth.command()
def status():
    """Check authentication status"""
    
    click.echo("🔐 Authentication Status")
    click.echo("=" * 40)
    
    # Check environment
    auth_enabled = os.getenv("GLEITZEIT_AUTH_ENABLED", "false").lower() == "true"
    click.echo(f"\n✓ Authentication Enabled: {auth_enabled}")
    
    if auth_enabled:
        # Show configuration
        click.echo("\n📋 Configuration:")
        click.echo(f"  Admin Email: {os.getenv('GLEITZEIT_AUTH_ADMIN_EMAIL', 'not set')}")
        click.echo(f"  JWT Secret: {'configured' if os.getenv('GLEITZEIT_AUTH_JWT_SECRET') else 'not set'}")
        click.echo(f"  Persistence: {os.getenv('GLEITZEIT_PERSISTENCE_TYPE', 'memory')}")
        
        # Show features
        click.echo("\n⚙️  Features:")
        features = [
            ('API Keys', 'GLEITZEIT_AUTH_API_KEYS'),
            ('JWT Tokens', 'GLEITZEIT_AUTH_JWT'),
            ('Sessions', 'GLEITZEIT_AUTH_SESSIONS'),
            ('Rate Limiting', 'GLEITZEIT_AUTH_RATE_LIMITING'),
            ('Audit Logging', 'GLEITZEIT_AUTH_AUDIT_LOG'),
            ('Ownership Filter', 'GLEITZEIT_AUTH_OWNERSHIP_FILTER'),
            ('User Registration', 'GLEITZEIT_AUTH_USER_REGISTRATION')
        ]
        
        for name, env_var in features:
            enabled = os.getenv(env_var, 'true').lower() == 'true'
            status = '✓' if enabled else '✗'
            click.echo(f"  [{status}] {name}")
    
    # Check config file
    config_file = Path.home() / ".gleitzeit" / "config.yaml"
    if config_file.exists():
        click.echo(f"\n📁 Config file: {config_file}")
    else:
        click.echo("\n📁 Config file: not found")
    
    # Check env file
    env_file = Path.home() / ".gleitzeit" / ".env"
    if env_file.exists():
        click.echo(f"🔑 Env file: {env_file}")
    else:
        click.echo("🔑 Env file: not found")
    
    if not auth_enabled:
        click.echo("\n💡 To enable authentication, run: gleitzeit auth setup")


if __name__ == "__main__":
    auth()