global:
  auto_restart: true
  auto_start: true
  connection_timeout: 10
  default_server_url: http://localhost:8000
  health_check_interval: 30
  max_retry_attempts: 3
providers:
  local_tools:
    class: providers.tool_provider.LocalToolsProvider
    config:
      name: local-tools
      server_url: http://localhost:8000
    description: Local utility tools
    enabled: false
    type: tool
  ollama:
    auto_discover_models: true
    class: my_local_llm_provider.OllamaProvider
    config:
      name: ollama
      ollama_url: http://localhost:11434
      server_url: http://localhost:8000
    description: Local Ollama LLM models
    enabled: true
    type: llm
